sudo: false
language: python
python:
  - "2.7"
branches:
  only: 
    - master
env:
  global:
    - GH_REF: github.com/otamachan2/sphinxcontrib-ros-slide.git
    - secure: "VAiZvzAs8+dSzybcZNDDFJNDxvJX5hKgi6vNxRUc3PjZhXBogses8zyZOuKhXjy+tWW8hofB3bqKbzTboWxMG++sjeg5CB194l34WS2GU5zNMhRSWOzVVqIXn6aJBFNYMzEViB4DezcXB2sQKw1P2C5DRpumvOzRKP660pOJfrTflWV5l107NGkElLmCFjLPQnDyoqqSDhypo8Tx624kEZCAXVEpXQBDHEoMyT2efSTKD9gHRKWkvNRlbHmj4JXIkBPAGi7BWSc91TpgzB4mppLcVC4mTlzQ3goquVT0oWurCvnCS8LHiatTg7rNZAWq3TongC9YPXO8BqRERvVuXU66fk7PO0ZgNRcGkmt/PdI+l2tLRc2EEsmj0G1YwCC1jlWRbLDCovN2geuf+PO/RTus+6XcExVPmEAW9fi38vRO/vmuXLPxq0FbdY4UZ7BCVF3FzJvNGxZquWL53lBbucoKlW4naRKpOmyGWjuZzdIDFI/JUL1ybpZKjjgogjbG8j7idTQFDJnXZmzDYlV4AN1RYg8tniz+i1Mxsk5/UvXj6wSaOY4JY4mtnsK8/PcsXWI91eE95WdQYzzUX7eDR115N3YPmtiwWmmgaup+ZY9ihFE4ivDolEBu7OFmE51g87/ffMO+9+44bNwaHkzmMwYb050O5tUKlWvgOUyGaP4="
install: 
  - pip install -q -r requirements.txt
  - pip install git+https://github.com/otamachan2/sphinxcontrib-ros.git
script:
  - make
  - cd _build/slides
  - git init
  - git config user.name "Travis CI"
  - git config user.email "otamachan@gmail.com"
  - touch .nojekyll
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1